version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    env_file: ./server/.env
    build: ./server
    ports:
      - "8080:8080"
