version: "3"
services:
  ui:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./server
    environment:
      - PORT=8080
      - PORT=localhost
      - MONGOURI=mongodb://localhost:27017/chatio
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
