version: "3.7"

services:
  client:
    container_name: client
    build:
      context: .
      target: development
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/bin
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server/src:/server/src
    ports:
      - 8080:8080
    env_file:
      - ./server/.env
